
blueprint:
  name: PV Heating Rod Automation with Real Surplus Calculation
  description: |
    Version 1.3.4
    This automation controls up to three heating rods based on the *actual* PV surplus,
    calculated as:
    
      PV Generation - Internal Consumption = Effective PV Surplus

    Features:
    - Safe switching with fixed 5-second delays between actions.
    - Configurable lock time after switching (default 2 minutes).
    - Automatic failsafe shutdown if outside time window or battery SOC is too low.
    - Automatic stage logging with effective surplus value.

  domain: automation
  source_url: "https://raw.githubusercontent.com/4gismo/homeassistant-blueprints/main/automation/pv_heating_rod/blueprint.yaml"

  input:
    pv_generation_sensor:
      name: PV Generation Sensor
      selector:
        entity:
          domain: sensor
    internal_consumption_sensor:
      name: Internal Consumption Sensor
      selector:
        entity:
          domain: sensor
    battery_soc_sensor:
      name: Battery SOC Sensor
      selector:
        entity:
          domain: sensor
    battery_limit:
      name: Minimum Battery SOC (%)
      default: 60
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          step: 1
    start_time:
      name: Automation Start Time
      default: "08:00:00"
      selector:
        time: {}
    end_time:
      name: Automation End Time
      default: "18:00:00"
      selector:
        time: {}
    lock_time_after_switching:
      name: Lock Time After Switching (minutes)
      default: 2
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: min
          step: 1

    stage_1_threshold:
      name: Minimum Effective PV Surplus for Stage 1 (1 kW total)
      default: 1000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_2_threshold:
      name: Minimum Effective PV Surplus for Stage 2 (2 kW total)
      default: 2000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_3_threshold:
      name: Minimum Effective PV Surplus for Stage 3 (3 kW total)
      default: 3000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_4_threshold:
      name: Minimum Effective PV Surplus for Stage 4 (4 kW total)
      default: 4000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_5_threshold:
      name: Minimum Effective PV Surplus for Stage 5 (5 kW total)
      default: 5000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_6_threshold:
      name: Minimum Effective PV Surplus for Stage 6 (6 kW total)
      default: 6000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    switch_p1:
      name: Switch for Heating Rod 1 (1 kW)
      selector:
        entity:
          domain: switch
    switch_p2:
      name: Switch for Heating Rod 2 (2 kW)
      selector:
        entity:
          domain: switch
    switch_p3:
      name: Switch for Heating Rod 3 (3 kW)
      selector:
        entity:
          domain: switch

trigger:
  - platform: state
    entity_id: !input pv_generation_sensor
  - platform: state
    entity_id: !input internal_consumption_sensor
  - platform: state
    entity_id: !input battery_soc_sensor
  - platform: time_pattern
    minutes: "/5"

condition:
  - condition: time
    after: !input start_time
    before: !input end_time
  - condition: numeric_state
    entity_id: !input battery_soc_sensor
    above: !input battery_limit

action:
  - variables:
      pv_generation: "{{ states(!input pv_generation_sensor) | float(0) }}"
      internal_consumption: "{{ states(!input internal_consumption_sensor) | float(0) }}"
      effective_surplus: "{{ pv_generation - internal_consumption }}"


  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: not
                conditions:
                  - condition: time
                    after: !input start_time
                    before: !input end_time
              - condition: not
                conditions:
                  - condition: numeric_state
                    entity_id: !input battery_soc_sensor
                    above: !input battery_limit
        sequence:
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p2
                - !input switch_p3

  - choose:

      - conditions:
          - condition: template
            value_template: "{{ effective_surplus > !input stage_6_threshold }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p1
          - delay: "00:00:05"
          - service: switch.turn_on
            target:
              entity_id: !input switch_p2
          - delay: "00:00:05"
          - service: switch.turn_on
            target:
              entity_id: !input switch_p3
          - service: persistent_notification.create
            data:
              title: "PV Heating Rod Automation"
              message: "Stage 6 active. Effective surplus: {{ effective_surplus }} W"

      - conditions:
          - condition: template
            value_template: "{{ effective_surplus > !input stage_5_threshold }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p2
          - delay: "00:00:05"
          - service: switch.turn_on
            target:
              entity_id: !input switch_p3
          - delay: "00:00:05"
          - service: switch.turn_off
            target:
              entity_id: !input switch_p1
          - service: persistent_notification.create
            data:
              title: "PV Heating Rod Automation"
              message: "Stage 5 active. Effective surplus: {{ effective_surplus }} W"

      - conditions:
          - condition: template
            value_template: "{{ effective_surplus > !input stage_4_threshold }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p1
          - delay: "00:00:05"
          - service: switch.turn_on
            target:
              entity_id: !input switch_p3
          - delay: "00:00:05"
          - service: switch.turn_off
            target:
              entity_id: !input switch_p2
          - service: persistent_notification.create
            data:
              title: "PV Heating Rod Automation"
              message: "Stage 4 active. Effective surplus: {{ effective_surplus }} W"

      - conditions:
          - condition: template
            value_template: "{{ effective_surplus > !input stage_3_threshold }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p3
          - delay: "00:00:05"
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p2
          - service: persistent_notification.create
            data:
              title: "PV Heating Rod Automation"
              message: "Stage 3 active. Effective surplus: {{ effective_surplus }} W"

      - conditions:
          - condition: template
            value_template: "{{ effective_surplus > !input stage_2_threshold }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p2
          - delay: "00:00:05"
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p3
          - service: persistent_notification.create
            data:
              title: "PV Heating Rod Automation"
              message: "Stage 2 active. Effective surplus: {{ effective_surplus }} W"

      - conditions:
          - condition: template
            value_template: "{{ effective_surplus > !input stage_1_threshold }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p1
          - delay: "00:00:05"
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p2
                - !input switch_p3
          - service: persistent_notification.create
            data:
              title: "PV Heating Rod Automation"
              message: "Stage 1 active. Effective surplus: {{ effective_surplus }} W"

      - conditions:
          - condition: template
            value_template: "{{ effective_surplus <= !input stage_1_threshold }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p2
                - !input switch_p3
          - service: persistent_notification.create
            data:
              title: "PV Heating Rod Automation"
              message: "Stage 0 active. All heating rods OFF. Effective surplus: {{ effective_surplus }} W"

  - delay:
      minutes: !input lock_time_after_switching

mode: restart
