blueprint:
  name: PV Heating Rod Automation (Custom Stages)
  description: |
    Version 1.0.0

    Controls up to three heating rods based on PV surplus and battery SOC.
    Each stage corresponds to a specific combination of heating rods according to PV surplus thresholds.
  domain: automation
  source_url: "https://raw.githubusercontent.com/4gismo/homeassistant-blueprints/main/automation/pv_heating_rod/blueprint.yaml"
  description: |
    Controls up to three heating rods based on PV surplus and battery SOC.
    Each stage corresponds to a specific combination of heating rods according to PV surplus thresholds.
  domain: automation
  input:
    pv_sensor:
      name: PV Surplus Sensor
      selector:
        entity:
          domain: sensor
    battery_soc:
      name: Battery SOC Sensor
      selector:
        entity:
          domain: sensor
    battery_limit:
      name: Minimum Battery SOC (%)
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          step: 1
    stage_1_threshold:
      name: Minimum PV Surplus for Stage 1 (1 kW total)
      default: 1000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_2_threshold:
      name: Minimum PV Surplus for Stage 2 (2 kW total)
      default: 2000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_3_threshold:
      name: Minimum PV Surplus for Stage 3 (3 kW total)
      default: 3000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_4_threshold:
      name: Minimum PV Surplus for Stage 4 (4 kW total)
      default: 4000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_5_threshold:
      name: Minimum PV Surplus for Stage 5 (5 kW total)
      default: 5000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    stage_6_threshold:
      name: Minimum PV Surplus for Stage 6 (6 kW total)
      default: 6000
      selector:
        number:
          min: 0
          max: 10000
          step: 100
          unit_of_measurement: W
    switch_p1:
      name: Switch for Heating Rod 1 (1 kW)
      selector:
        entity:
          domain: switch
    switch_p2:
      name: Switch for Heating Rod 2 (2 kW)
      selector:
        entity:
          domain: switch
    switch_p3:
      name: Switch for Heating Rod 3 (3 kW)
      selector:
        entity:
          domain: switch

trigger:
  - platform: state
    entity_id: !input pv_sensor
  - platform: state
    entity_id: !input battery_soc
  - platform: time_pattern
    minutes: "/5"

condition:
  - condition: numeric_state
    entity_id: !input battery_soc
    above: !input battery_limit

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            above: !input stage_6_threshold
        sequence:
          - service: switch.turn_on
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p2
                - !input switch_p3
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            above: !input stage_5_threshold
        sequence:
          - service: switch.turn_on
            target:
              entity_id:
                - !input switch_p2
                - !input switch_p3
          - service: switch.turn_off
            target:
              entity_id: !input switch_p1
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            above: !input stage_4_threshold
        sequence:
          - service: switch.turn_on
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p3
          - service: switch.turn_off
            target:
              entity_id: !input switch_p2
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            above: !input stage_3_threshold
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p3
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p2
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            above: !input stage_2_threshold
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p2
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p3
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            above: !input stage_1_threshold
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input switch_p1
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p2
                - !input switch_p3
      - conditions:
          - condition: numeric_state
            entity_id: !input pv_sensor
            below: !input stage_1_threshold
        sequence:
          - service: switch.turn_off
            target:
              entity_id:
                - !input switch_p1
                - !input switch_p2
                - !input switch_p3

mode: restart
